# **Курс "Програмування на мові Python"**

##### Викладачі:
##### Борисенко Павло Борисович
##### Щьоголєв Максим Олегович


## **Практичне зайняття №8**

### Тема: "Робота з функціями. Локальні та глобальні змінні"

### **Завдання 1 (3 бали)**

**Підрахувати визначник матриці, використовуючи правило перестановок.**

Функція random_matrix() призначена для створення квадратної матриці випадкових чисел. Її змінювати непотрібно.

Приклад використання методу permutations() для створення списку перестановок також подається у комірці з кодом.

1) Створити 3 функції: функцію створення списку перестановок, функцію підрахунку добутків та функцію підрахунку загальної суми.

2) Кожна функція має супроводжуватись рядком документації, що буде коротко описувати її призначення.

3) Розмірність квадратної матриці має вводитись користувачем з клавіатури. Підрахунки виконувати лише в тому разі, якщо користувач введе ціле додатне число.

4) Загальний результат повинен підраховуватись за допомогою композиції функцій.

За бажання можна перевірити правильність роботи програми за допомогою функції np.linalg.det(a).

In [1]:
import numpy as np
import itertools
import math

while True:
    order_test = input("Enter the order: ")
    try:
        order = int(order_test)
        if order <= 0:
            print("incorrect data")
            continue
    except ValueError:
        print("incorrect data")
    else:
        break

def random_matrix(dim):
    """
    The function generates dim x dim array of integers
    between 0 and 10.
    """
    matrix = np.random.randint(10, size = (dim, dim))
    return matrix

def permutation(arg):
    """
    The function displays all possible 
    permutations of rows of a matrix
    """
    variants = list(itertools.permutations(arg, order))
    return variants

def multiples(number):
    """
    The function calculates all the required products
    to calculate the determinant
    """
    global counter
    counter = 0
    mult = 1
    for x in range(0, order):
        mult_new = matrix[x][inversions[number][x]-1] #compares the corresponding coefficients
        mult *= mult_new

    i = inversions[number] #it will count the number of inversions
    i = list(i)
    while len(i)> 1:
        highest = max(i)
        if i.index(highest) < order-1:
            counter += len(i[i.index(highest):]) - 1 
            del i[i.index(highest)]
        else:
            del i[i.index(highest)]
    return mult

def add(result):
    """
    The function calculates the total amount
    """
    global det
    if counter%2 == 0:
        det += result
        return det
    else:
        det += -result
        return det

matrix = random_matrix(order)
lst = list(range(1, order+1))
inversions = permutation(lst)
number = -1
det = 0
counter = 0
while number < math.factorial(order)-1: #composing
    number += 1
    comp = add(multiples(number))

print(matrix)
print("inversions:", inversions)
print("determinant:", comp)

incorrect data
incorrect data
incorrect data
[[3 4 6 7 3]
 [0 7 7 7 7]
 [8 1 5 9 6]
 [8 8 9 2 5]
 [3 6 5 9 1]]
inversions: [(1, 2, 3, 4, 5), (1, 2, 3, 5, 4), (1, 2, 4, 3, 5), (1, 2, 4, 5, 3), (1, 2, 5, 3, 4), (1, 2, 5, 4, 3), (1, 3, 2, 4, 5), (1, 3, 2, 5, 4), (1, 3, 4, 2, 5), (1, 3, 4, 5, 2), (1, 3, 5, 2, 4), (1, 3, 5, 4, 2), (1, 4, 2, 3, 5), (1, 4, 2, 5, 3), (1, 4, 3, 2, 5), (1, 4, 3, 5, 2), (1, 4, 5, 2, 3), (1, 4, 5, 3, 2), (1, 5, 2, 3, 4), (1, 5, 2, 4, 3), (1, 5, 3, 2, 4), (1, 5, 3, 4, 2), (1, 5, 4, 2, 3), (1, 5, 4, 3, 2), (2, 1, 3, 4, 5), (2, 1, 3, 5, 4), (2, 1, 4, 3, 5), (2, 1, 4, 5, 3), (2, 1, 5, 3, 4), (2, 1, 5, 4, 3), (2, 3, 1, 4, 5), (2, 3, 1, 5, 4), (2, 3, 4, 1, 5), (2, 3, 4, 5, 1), (2, 3, 5, 1, 4), (2, 3, 5, 4, 1), (2, 4, 1, 3, 5), (2, 4, 1, 5, 3), (2, 4, 3, 1, 5), (2, 4, 3, 5, 1), (2, 4, 5, 1, 3), (2, 4, 5, 3, 1), (2, 5, 1, 3, 4), (2, 5, 1, 4, 3), (2, 5, 3, 1, 4), (2, 5, 3, 4, 1), (2, 5, 4, 1, 3), (2, 5, 4, 3, 1), (3, 1, 2, 4, 5), (3, 1, 2, 5, 4), (3, 1, 4, 2, 5), (3, 1, 4,